### ISSUE TITLE
API for ClearPass Upgrade

### ISSUE THREAD

**Issue by akhi9** [santsys/aruba-clearpass-api#3]
@santsys Is there an API (or without using the GUI of clearpass) to upgrade the cluster nodes?

**Comment by santsys** [comment]
@akhi9 I don't believe there is a way to specifically trigger the upgrade process with the rest APIs.

**Comment by akhi9** [comment]
@santsys is this intentional from ClearPass's side? 
One workaround I have come across is to capture the GUI interaction that occurs when you load the upgrade screens(using Fiddler), but it seems to be getting pretty complicated.
Is there any workaround for this then?

**Comment by santsys** [comment]
Not that I'm aware of. You could post in the Aruba Community about it and someone may be able to give you a better answer... https://community.arubanetworks.com/home
